spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
          client:
            registration:
              qq:
                client-id: your-qq-app-id
                client-secret: your-qq-app-secret
                client-authentication-method: post # QQ要求client_secret通过POST参数传递
                authorization-grant-type: authorization_code
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                scope: get_user_info
                client-name: QQ
            provider:
              qq:
                authorization-uri: https://graph.qq.com/oauth2.0/authorize
                token-uri: https://graph.qq.com/oauth2.0/token
                user-info-uri: https://graph.qq.com/oauth2.0/me
                user-name-attribute: openid # QQ使用openid作为用户唯一标识

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出sql语句
    # 默认驼峰式命名
    map-underscore-to-camel-case: true
  # 自定义方法默认的mapper文件位置
  mapper-locations: classpath:mapper/*.xml

# JWT 相关配置
jwt:
  # 用于JWT签名的密钥。这个密钥应该是一个长而复杂的字符串。
  # 在生产环境中，强烈建议使用一个安全、随机生成的密钥，并将其安全地存储（例如，通过环境变量）。
  # 这里提供的密钥仅用于演示目的，在真实应用中必须更换。
  # 对于HS256算法，密钥长度必须至少为256位（32字节）。
  secret: c2VjdXJpdHlqc3BlY3RzcHJpbmduanB0dG9rZW5zYW1wbGVzZWNyZXRrZXkyNTZiaXRz # 一个安全的Base64编码密钥
  expiration: 3600

# Spring Security OAuth2 Client Configuration